### ISSUE TITLE
Need help to deploy

### ISSUE THREAD

**Issue by abhiesa** [uetchy/wercker-step-gh-pages#1]
Trying to use your plugin in wercker but all deploys are failing. 
Trying to find out some help, but didn't find any.
Read your SH file, still many things are unclear, as i am not a unix guy.
my werkerfile : [wercker.yml](https://github.com/abhiesa/abhiesa.github.io/blob/source/wercker.yml)
my unfortunate logs of failed deploys [logs](https://app.wercker.com/#applications/55c523d5ec6f880650000997)
Could you please help me, I am try to help ppl in writing blog, and found hugo+ githubi + werker as best bet to encourage and motivate ppl  write, but last part his where things got painful.
Hoping, when ever you see this, you can help me, so that i can help others.

```
export WERCKER_STEP_ROOT="/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6"
export WERCKER_STEP_ID="gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6"
export WERCKER_STEP_OWNER="uetchy"
export WERCKER_STEP_NAME="gh-pages"
export WERCKER_REPORT_NUMBERS_FILE="/report/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/artifacts"
export WERCKER_GH_PAGES_PATH="public"
export WERCKER_GH_PAGES_TOKEN="$GIT_TOKEN"
export WERCKER_GH_PAGES_REPO="abhiesa/abhiesa.github.io"
export WERCKER_GH_PAGES_DOMAIN="github.com"
source "/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh" < /dev/null
Using 'abhiesa/abhiesa.github.io'
Using branch 'master'
Using 'public' as root dir instead of git root
Generating CNAME for 'github.com'
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 36: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 37: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 38: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 39: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 40: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 41: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 42: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 43: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 44: git: command not found
/pipeline/gh-pages-cb3c0f75-3636-472a-89ed-0503179abac6/run.sh: line 47: warning: command not found
failed: Failed deploying to Github Pages
```

**Comment by uetchy** [comment]
Did you create default Docker-based(Ewok) stack? This step is only available in Classic(Andorian) stack.

Try to change stacks from Docker to Classic at "Infrastructure stack" section in settings page.

**Comment by uetchy** [comment]
I added more details of usage to [README](https://github.com/uetchy/wercker-step-gh-pages/blob/master/README.md).

Anyway you can use Docker-based stack but you will need to find out Docker images which have `git` command.
Default wercker box of Classic stack already have `git` so it's easier than Docker-based stack IMO.

### Update

If you don't need custom domains, you can omit `domain: github.com` section.

**Comment by abhiesa** [comment]
Great. Thanks a lot. Yes am using docker based setup, will try to change it. 
Now, I realised that it is a container issue. :)

I think, it now important to notify GOHugo (may be with a pull request), so that deployment docs were need to be a little more tweaked.
5 Stars for you sir. :)
